fix crash on app start due to uninitialized application
would log

    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{de.qrdn.phy2music/de.qrdn.phy2music.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference